syntax = "proto3";

//option go_package = "github.com/Wenev/Survace/notification-service/internal/adapters/inbound/dto";
option go_package = "github.com/Wenev/Survace/proto/gen/dto";
import "google/protobuf/timestamp.proto";

message Notification {
  int32 id = 1;
  int32 user_id = 2;
  string type = 3;
  string content = 4;
  bool read = 5;
  google.protobuf.Timestamp created_at = 6;
}

message GetNotificationsByUserIDRequest {
  int32 user_id = 1;
}

message GetNotificationsByUserIDResponse {
  int32 code = 1;
  string message = 2;
  repeated Notification notifications = 3;
}

message MarkNotificationRequest {
  int32 notification_id = 1;
}

message MarkNotificationResponse {
  int32 code = 1;
  string message = 2;
}

message DeleteNotificationRequest {
  int32 notification_id = 1;
}

message DeleteNotificationResponse {
  int32 code = 1;
  string message = 2;
}

message DeleteAllNotificationsByUserIDRequest {
  int32 user_id = 1;
}

message DeleteAllNotificationsByUserIDResponse {
  int32 code = 1;
  string message = 2;
}

message SendNotificationRequest {
  int32 user_id = 1;
  string type = 2;
  string content = 3;
}

message SendNotificationResponse {
  int32 code = 1;
  string message = 2;
  Notification notification = 3;
}
