// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: controller/video_controller.proto

package controller

import (
	dto "github.com/Acad600-TPA/WEB-WE-251/brainrot-service/internal/adapters/inbound/dto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_controller_video_controller_proto protoreflect.FileDescriptor

const file_controller_video_controller_proto_rawDesc = "" +
	"\n" +
	"!controller/video_controller.proto\x1a\x0fdto/video.proto2\xf3\n" +
	"\n" +
	"\x0fBrainrotService\x128\n" +
	"\vUploadVideo\x12\x13.UploadVideoRequest\x1a\x14.UploadVideoResponse\x12;\n" +
	"\fGetVideoByID\x12\x14.GetVideoByIDRequest\x1a\x15.GetVideoByIDResponse\x12;\n" +
	"\fGetUserVideo\x12\x14.GetUserVideoRequest\x1a\x15.GetUserVideoResponse\x12D\n" +
	"\x0fDeleteUserVideo\x12\x17.DeleteUserVideoRequest\x1a\x18.DeleteUserVideoResponse\x125\n" +
	"\n" +
	"AddComment\x12\x12.AddCommentRequest\x1a\x13.AddCommentResponse\x12M\n" +
	"\x12GetCommentsByVideo\x12\x1a.GetCommentsByVideoRequest\x1a\x1b.GetCommentsByVideoResponse\x12>\n" +
	"\rDeleteComment\x12\x15.DeleteCommentRequest\x1a\x16.DeleteCommentResponse\x12/\n" +
	"\bAddReply\x12\x10.AddReplyRequest\x1a\x11.AddReplyResponse\x12P\n" +
	"\x13GetRepliesByComment\x12\x1b.GetRepliesByCommentRequest\x1a\x1c.GetRepliesByCommentResponse\x128\n" +
	"\vDeleteReply\x12\x13.DeleteReplyRequest\x1a\x14.DeleteReplyResponse\x122\n" +
	"\tLikeVideo\x12\x11.LikeVideoRequest\x1a\x12.LikeVideoResponse\x128\n" +
	"\vUnlikeVideo\x12\x13.UnlikeVideoRequest\x1a\x14.UnlikeVideoResponse\x12;\n" +
	"\fIsVideoLiked\x12\x14.IsVideoLikedRequest\x1a\x15.IsVideoLikedResponse\x128\n" +
	"\vLikeComment\x12\x13.LikeCommentRequest\x1a\x14.LikeCommentResponse\x12>\n" +
	"\rUnlikeComment\x12\x15.UnlikeCommentRequest\x1a\x16.UnlikeCommentResponse\x12A\n" +
	"\x0eIsCommentLiked\x12\x16.IsCommentLikedRequest\x1a\x17.IsCommentLikedResponse\x122\n" +
	"\tLikeReply\x12\x11.LikeReplyRequest\x1a\x12.LikeReplyResponse\x128\n" +
	"\vUnlikeReply\x12\x13.UnlikeReplyRequest\x1a\x14.UnlikeReplyResponse\x12;\n" +
	"\fIsReplyLiked\x12\x14.IsReplyLikedRequest\x1a\x15.IsReplyLikedResponse\x125\n" +
	"\n" +
	"WatchVideo\x12\x12.WatchVideoRequest\x1a\x13.WatchVideoResponse\x12Y\n" +
	"\x16GetRandomFeedLoggedOut\x12\x1e.GetRandomFeedLoggedOutRequest\x1a\x1f.GetRandomFeedLoggedOutResponse\x12>\n" +
	"\rGetRandomFeed\x12\x15.GetRandomFeedRequest\x1a\x16.GetRandomFeedResponseBYZWgithub.com/Acad600-TPA/WEB-WE-251/brainrot-service/internal/adapters/inbound/controllerb\x06proto3"

var file_controller_video_controller_proto_goTypes = []any{
	(*dto.UploadVideoRequest)(nil),             // 0: UploadVideoRequest
	(*dto.GetVideoByIDRequest)(nil),            // 1: GetVideoByIDRequest
	(*dto.GetUserVideoRequest)(nil),            // 2: GetUserVideoRequest
	(*dto.DeleteUserVideoRequest)(nil),         // 3: DeleteUserVideoRequest
	(*dto.AddCommentRequest)(nil),              // 4: AddCommentRequest
	(*dto.GetCommentsByVideoRequest)(nil),      // 5: GetCommentsByVideoRequest
	(*dto.DeleteCommentRequest)(nil),           // 6: DeleteCommentRequest
	(*dto.AddReplyRequest)(nil),                // 7: AddReplyRequest
	(*dto.GetRepliesByCommentRequest)(nil),     // 8: GetRepliesByCommentRequest
	(*dto.DeleteReplyRequest)(nil),             // 9: DeleteReplyRequest
	(*dto.LikeVideoRequest)(nil),               // 10: LikeVideoRequest
	(*dto.UnlikeVideoRequest)(nil),             // 11: UnlikeVideoRequest
	(*dto.IsVideoLikedRequest)(nil),            // 12: IsVideoLikedRequest
	(*dto.LikeCommentRequest)(nil),             // 13: LikeCommentRequest
	(*dto.UnlikeCommentRequest)(nil),           // 14: UnlikeCommentRequest
	(*dto.IsCommentLikedRequest)(nil),          // 15: IsCommentLikedRequest
	(*dto.LikeReplyRequest)(nil),               // 16: LikeReplyRequest
	(*dto.UnlikeReplyRequest)(nil),             // 17: UnlikeReplyRequest
	(*dto.IsReplyLikedRequest)(nil),            // 18: IsReplyLikedRequest
	(*dto.WatchVideoRequest)(nil),              // 19: WatchVideoRequest
	(*dto.GetRandomFeedLoggedOutRequest)(nil),  // 20: GetRandomFeedLoggedOutRequest
	(*dto.GetRandomFeedRequest)(nil),           // 21: GetRandomFeedRequest
	(*dto.UploadVideoResponse)(nil),            // 22: UploadVideoResponse
	(*dto.GetVideoByIDResponse)(nil),           // 23: GetVideoByIDResponse
	(*dto.GetUserVideoResponse)(nil),           // 24: GetUserVideoResponse
	(*dto.DeleteUserVideoResponse)(nil),        // 25: DeleteUserVideoResponse
	(*dto.AddCommentResponse)(nil),             // 26: AddCommentResponse
	(*dto.GetCommentsByVideoResponse)(nil),     // 27: GetCommentsByVideoResponse
	(*dto.DeleteCommentResponse)(nil),          // 28: DeleteCommentResponse
	(*dto.AddReplyResponse)(nil),               // 29: AddReplyResponse
	(*dto.GetRepliesByCommentResponse)(nil),    // 30: GetRepliesByCommentResponse
	(*dto.DeleteReplyResponse)(nil),            // 31: DeleteReplyResponse
	(*dto.LikeVideoResponse)(nil),              // 32: LikeVideoResponse
	(*dto.UnlikeVideoResponse)(nil),            // 33: UnlikeVideoResponse
	(*dto.IsVideoLikedResponse)(nil),           // 34: IsVideoLikedResponse
	(*dto.LikeCommentResponse)(nil),            // 35: LikeCommentResponse
	(*dto.UnlikeCommentResponse)(nil),          // 36: UnlikeCommentResponse
	(*dto.IsCommentLikedResponse)(nil),         // 37: IsCommentLikedResponse
	(*dto.LikeReplyResponse)(nil),              // 38: LikeReplyResponse
	(*dto.UnlikeReplyResponse)(nil),            // 39: UnlikeReplyResponse
	(*dto.IsReplyLikedResponse)(nil),           // 40: IsReplyLikedResponse
	(*dto.WatchVideoResponse)(nil),             // 41: WatchVideoResponse
	(*dto.GetRandomFeedLoggedOutResponse)(nil), // 42: GetRandomFeedLoggedOutResponse
	(*dto.GetRandomFeedResponse)(nil),          // 43: GetRandomFeedResponse
}
var file_controller_video_controller_proto_depIdxs = []int32{
	0,  // 0: BrainrotService.UploadVideo:input_type -> UploadVideoRequest
	1,  // 1: BrainrotService.GetVideoByID:input_type -> GetVideoByIDRequest
	2,  // 2: BrainrotService.GetUserVideo:input_type -> GetUserVideoRequest
	3,  // 3: BrainrotService.DeleteUserVideo:input_type -> DeleteUserVideoRequest
	4,  // 4: BrainrotService.AddComment:input_type -> AddCommentRequest
	5,  // 5: BrainrotService.GetCommentsByVideo:input_type -> GetCommentsByVideoRequest
	6,  // 6: BrainrotService.DeleteComment:input_type -> DeleteCommentRequest
	7,  // 7: BrainrotService.AddReply:input_type -> AddReplyRequest
	8,  // 8: BrainrotService.GetRepliesByComment:input_type -> GetRepliesByCommentRequest
	9,  // 9: BrainrotService.DeleteReply:input_type -> DeleteReplyRequest
	10, // 10: BrainrotService.LikeVideo:input_type -> LikeVideoRequest
	11, // 11: BrainrotService.UnlikeVideo:input_type -> UnlikeVideoRequest
	12, // 12: BrainrotService.IsVideoLiked:input_type -> IsVideoLikedRequest
	13, // 13: BrainrotService.LikeComment:input_type -> LikeCommentRequest
	14, // 14: BrainrotService.UnlikeComment:input_type -> UnlikeCommentRequest
	15, // 15: BrainrotService.IsCommentLiked:input_type -> IsCommentLikedRequest
	16, // 16: BrainrotService.LikeReply:input_type -> LikeReplyRequest
	17, // 17: BrainrotService.UnlikeReply:input_type -> UnlikeReplyRequest
	18, // 18: BrainrotService.IsReplyLiked:input_type -> IsReplyLikedRequest
	19, // 19: BrainrotService.WatchVideo:input_type -> WatchVideoRequest
	20, // 20: BrainrotService.GetRandomFeedLoggedOut:input_type -> GetRandomFeedLoggedOutRequest
	21, // 21: BrainrotService.GetRandomFeed:input_type -> GetRandomFeedRequest
	22, // 22: BrainrotService.UploadVideo:output_type -> UploadVideoResponse
	23, // 23: BrainrotService.GetVideoByID:output_type -> GetVideoByIDResponse
	24, // 24: BrainrotService.GetUserVideo:output_type -> GetUserVideoResponse
	25, // 25: BrainrotService.DeleteUserVideo:output_type -> DeleteUserVideoResponse
	26, // 26: BrainrotService.AddComment:output_type -> AddCommentResponse
	27, // 27: BrainrotService.GetCommentsByVideo:output_type -> GetCommentsByVideoResponse
	28, // 28: BrainrotService.DeleteComment:output_type -> DeleteCommentResponse
	29, // 29: BrainrotService.AddReply:output_type -> AddReplyResponse
	30, // 30: BrainrotService.GetRepliesByComment:output_type -> GetRepliesByCommentResponse
	31, // 31: BrainrotService.DeleteReply:output_type -> DeleteReplyResponse
	32, // 32: BrainrotService.LikeVideo:output_type -> LikeVideoResponse
	33, // 33: BrainrotService.UnlikeVideo:output_type -> UnlikeVideoResponse
	34, // 34: BrainrotService.IsVideoLiked:output_type -> IsVideoLikedResponse
	35, // 35: BrainrotService.LikeComment:output_type -> LikeCommentResponse
	36, // 36: BrainrotService.UnlikeComment:output_type -> UnlikeCommentResponse
	37, // 37: BrainrotService.IsCommentLiked:output_type -> IsCommentLikedResponse
	38, // 38: BrainrotService.LikeReply:output_type -> LikeReplyResponse
	39, // 39: BrainrotService.UnlikeReply:output_type -> UnlikeReplyResponse
	40, // 40: BrainrotService.IsReplyLiked:output_type -> IsReplyLikedResponse
	41, // 41: BrainrotService.WatchVideo:output_type -> WatchVideoResponse
	42, // 42: BrainrotService.GetRandomFeedLoggedOut:output_type -> GetRandomFeedLoggedOutResponse
	43, // 43: BrainrotService.GetRandomFeed:output_type -> GetRandomFeedResponse
	22, // [22:44] is the sub-list for method output_type
	0,  // [0:22] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_controller_video_controller_proto_init() }
func file_controller_video_controller_proto_init() {
	if File_controller_video_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_video_controller_proto_rawDesc), len(file_controller_video_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_video_controller_proto_goTypes,
		DependencyIndexes: file_controller_video_controller_proto_depIdxs,
	}.Build()
	File_controller_video_controller_proto = out.File
	file_controller_video_controller_proto_goTypes = nil
	file_controller_video_controller_proto_depIdxs = nil
}
