// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: controller/video_controller.proto

package controller

import (
	context "context"
	dto "github.com/Acad600-TPA/WEB-WE-251/brainrot-service/internal/adapters/inbound/dto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrainrotService_UploadVideo_FullMethodName            = "/BrainrotService/UploadVideo"
	BrainrotService_GetVideoByID_FullMethodName           = "/BrainrotService/GetVideoByID"
	BrainrotService_GetUserVideo_FullMethodName           = "/BrainrotService/GetUserVideo"
	BrainrotService_DeleteUserVideo_FullMethodName        = "/BrainrotService/DeleteUserVideo"
	BrainrotService_AddComment_FullMethodName             = "/BrainrotService/AddComment"
	BrainrotService_GetCommentsByVideo_FullMethodName     = "/BrainrotService/GetCommentsByVideo"
	BrainrotService_DeleteComment_FullMethodName          = "/BrainrotService/DeleteComment"
	BrainrotService_AddReply_FullMethodName               = "/BrainrotService/AddReply"
	BrainrotService_GetRepliesByComment_FullMethodName    = "/BrainrotService/GetRepliesByComment"
	BrainrotService_DeleteReply_FullMethodName            = "/BrainrotService/DeleteReply"
	BrainrotService_LikeVideo_FullMethodName              = "/BrainrotService/LikeVideo"
	BrainrotService_UnlikeVideo_FullMethodName            = "/BrainrotService/UnlikeVideo"
	BrainrotService_IsVideoLiked_FullMethodName           = "/BrainrotService/IsVideoLiked"
	BrainrotService_LikeComment_FullMethodName            = "/BrainrotService/LikeComment"
	BrainrotService_UnlikeComment_FullMethodName          = "/BrainrotService/UnlikeComment"
	BrainrotService_IsCommentLiked_FullMethodName         = "/BrainrotService/IsCommentLiked"
	BrainrotService_LikeReply_FullMethodName              = "/BrainrotService/LikeReply"
	BrainrotService_UnlikeReply_FullMethodName            = "/BrainrotService/UnlikeReply"
	BrainrotService_IsReplyLiked_FullMethodName           = "/BrainrotService/IsReplyLiked"
	BrainrotService_WatchVideo_FullMethodName             = "/BrainrotService/WatchVideo"
	BrainrotService_GetRandomFeedLoggedOut_FullMethodName = "/BrainrotService/GetRandomFeedLoggedOut"
	BrainrotService_GetRandomFeed_FullMethodName          = "/BrainrotService/GetRandomFeed"
)

// BrainrotServiceClient is the client API for BrainrotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrainrotServiceClient interface {
	// Video
	UploadVideo(ctx context.Context, in *dto.UploadVideoRequest, opts ...grpc.CallOption) (*dto.UploadVideoResponse, error)
	GetVideoByID(ctx context.Context, in *dto.GetVideoByIDRequest, opts ...grpc.CallOption) (*dto.GetVideoByIDResponse, error)
	GetUserVideo(ctx context.Context, in *dto.GetUserVideoRequest, opts ...grpc.CallOption) (*dto.GetUserVideoResponse, error)
	DeleteUserVideo(ctx context.Context, in *dto.DeleteUserVideoRequest, opts ...grpc.CallOption) (*dto.DeleteUserVideoResponse, error)
	// Comment
	AddComment(ctx context.Context, in *dto.AddCommentRequest, opts ...grpc.CallOption) (*dto.AddCommentResponse, error)
	GetCommentsByVideo(ctx context.Context, in *dto.GetCommentsByVideoRequest, opts ...grpc.CallOption) (*dto.GetCommentsByVideoResponse, error)
	DeleteComment(ctx context.Context, in *dto.DeleteCommentRequest, opts ...grpc.CallOption) (*dto.DeleteCommentResponse, error)
	// Reply
	AddReply(ctx context.Context, in *dto.AddReplyRequest, opts ...grpc.CallOption) (*dto.AddReplyResponse, error)
	GetRepliesByComment(ctx context.Context, in *dto.GetRepliesByCommentRequest, opts ...grpc.CallOption) (*dto.GetRepliesByCommentResponse, error)
	DeleteReply(ctx context.Context, in *dto.DeleteReplyRequest, opts ...grpc.CallOption) (*dto.DeleteReplyResponse, error)
	// Like Video
	LikeVideo(ctx context.Context, in *dto.LikeVideoRequest, opts ...grpc.CallOption) (*dto.LikeVideoResponse, error)
	UnlikeVideo(ctx context.Context, in *dto.UnlikeVideoRequest, opts ...grpc.CallOption) (*dto.UnlikeVideoResponse, error)
	IsVideoLiked(ctx context.Context, in *dto.IsVideoLikedRequest, opts ...grpc.CallOption) (*dto.IsVideoLikedResponse, error)
	// Like Comment
	LikeComment(ctx context.Context, in *dto.LikeCommentRequest, opts ...grpc.CallOption) (*dto.LikeCommentResponse, error)
	UnlikeComment(ctx context.Context, in *dto.UnlikeCommentRequest, opts ...grpc.CallOption) (*dto.UnlikeCommentResponse, error)
	IsCommentLiked(ctx context.Context, in *dto.IsCommentLikedRequest, opts ...grpc.CallOption) (*dto.IsCommentLikedResponse, error)
	// Like Reply
	LikeReply(ctx context.Context, in *dto.LikeReplyRequest, opts ...grpc.CallOption) (*dto.LikeReplyResponse, error)
	UnlikeReply(ctx context.Context, in *dto.UnlikeReplyRequest, opts ...grpc.CallOption) (*dto.UnlikeReplyResponse, error)
	IsReplyLiked(ctx context.Context, in *dto.IsReplyLikedRequest, opts ...grpc.CallOption) (*dto.IsReplyLikedResponse, error)
	// WatchHistory & Feed
	WatchVideo(ctx context.Context, in *dto.WatchVideoRequest, opts ...grpc.CallOption) (*dto.WatchVideoResponse, error)
	GetRandomFeedLoggedOut(ctx context.Context, in *dto.GetRandomFeedLoggedOutRequest, opts ...grpc.CallOption) (*dto.GetRandomFeedLoggedOutResponse, error)
	GetRandomFeed(ctx context.Context, in *dto.GetRandomFeedRequest, opts ...grpc.CallOption) (*dto.GetRandomFeedResponse, error)
}

type brainrotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrainrotServiceClient(cc grpc.ClientConnInterface) BrainrotServiceClient {
	return &brainrotServiceClient{cc}
}

func (c *brainrotServiceClient) UploadVideo(ctx context.Context, in *dto.UploadVideoRequest, opts ...grpc.CallOption) (*dto.UploadVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.UploadVideoResponse)
	err := c.cc.Invoke(ctx, BrainrotService_UploadVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) GetVideoByID(ctx context.Context, in *dto.GetVideoByIDRequest, opts ...grpc.CallOption) (*dto.GetVideoByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.GetVideoByIDResponse)
	err := c.cc.Invoke(ctx, BrainrotService_GetVideoByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) GetUserVideo(ctx context.Context, in *dto.GetUserVideoRequest, opts ...grpc.CallOption) (*dto.GetUserVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.GetUserVideoResponse)
	err := c.cc.Invoke(ctx, BrainrotService_GetUserVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) DeleteUserVideo(ctx context.Context, in *dto.DeleteUserVideoRequest, opts ...grpc.CallOption) (*dto.DeleteUserVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.DeleteUserVideoResponse)
	err := c.cc.Invoke(ctx, BrainrotService_DeleteUserVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) AddComment(ctx context.Context, in *dto.AddCommentRequest, opts ...grpc.CallOption) (*dto.AddCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.AddCommentResponse)
	err := c.cc.Invoke(ctx, BrainrotService_AddComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) GetCommentsByVideo(ctx context.Context, in *dto.GetCommentsByVideoRequest, opts ...grpc.CallOption) (*dto.GetCommentsByVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.GetCommentsByVideoResponse)
	err := c.cc.Invoke(ctx, BrainrotService_GetCommentsByVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) DeleteComment(ctx context.Context, in *dto.DeleteCommentRequest, opts ...grpc.CallOption) (*dto.DeleteCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.DeleteCommentResponse)
	err := c.cc.Invoke(ctx, BrainrotService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) AddReply(ctx context.Context, in *dto.AddReplyRequest, opts ...grpc.CallOption) (*dto.AddReplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.AddReplyResponse)
	err := c.cc.Invoke(ctx, BrainrotService_AddReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) GetRepliesByComment(ctx context.Context, in *dto.GetRepliesByCommentRequest, opts ...grpc.CallOption) (*dto.GetRepliesByCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.GetRepliesByCommentResponse)
	err := c.cc.Invoke(ctx, BrainrotService_GetRepliesByComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) DeleteReply(ctx context.Context, in *dto.DeleteReplyRequest, opts ...grpc.CallOption) (*dto.DeleteReplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.DeleteReplyResponse)
	err := c.cc.Invoke(ctx, BrainrotService_DeleteReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) LikeVideo(ctx context.Context, in *dto.LikeVideoRequest, opts ...grpc.CallOption) (*dto.LikeVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.LikeVideoResponse)
	err := c.cc.Invoke(ctx, BrainrotService_LikeVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) UnlikeVideo(ctx context.Context, in *dto.UnlikeVideoRequest, opts ...grpc.CallOption) (*dto.UnlikeVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.UnlikeVideoResponse)
	err := c.cc.Invoke(ctx, BrainrotService_UnlikeVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) IsVideoLiked(ctx context.Context, in *dto.IsVideoLikedRequest, opts ...grpc.CallOption) (*dto.IsVideoLikedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.IsVideoLikedResponse)
	err := c.cc.Invoke(ctx, BrainrotService_IsVideoLiked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) LikeComment(ctx context.Context, in *dto.LikeCommentRequest, opts ...grpc.CallOption) (*dto.LikeCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.LikeCommentResponse)
	err := c.cc.Invoke(ctx, BrainrotService_LikeComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) UnlikeComment(ctx context.Context, in *dto.UnlikeCommentRequest, opts ...grpc.CallOption) (*dto.UnlikeCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.UnlikeCommentResponse)
	err := c.cc.Invoke(ctx, BrainrotService_UnlikeComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) IsCommentLiked(ctx context.Context, in *dto.IsCommentLikedRequest, opts ...grpc.CallOption) (*dto.IsCommentLikedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.IsCommentLikedResponse)
	err := c.cc.Invoke(ctx, BrainrotService_IsCommentLiked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) LikeReply(ctx context.Context, in *dto.LikeReplyRequest, opts ...grpc.CallOption) (*dto.LikeReplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.LikeReplyResponse)
	err := c.cc.Invoke(ctx, BrainrotService_LikeReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) UnlikeReply(ctx context.Context, in *dto.UnlikeReplyRequest, opts ...grpc.CallOption) (*dto.UnlikeReplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.UnlikeReplyResponse)
	err := c.cc.Invoke(ctx, BrainrotService_UnlikeReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) IsReplyLiked(ctx context.Context, in *dto.IsReplyLikedRequest, opts ...grpc.CallOption) (*dto.IsReplyLikedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.IsReplyLikedResponse)
	err := c.cc.Invoke(ctx, BrainrotService_IsReplyLiked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) WatchVideo(ctx context.Context, in *dto.WatchVideoRequest, opts ...grpc.CallOption) (*dto.WatchVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.WatchVideoResponse)
	err := c.cc.Invoke(ctx, BrainrotService_WatchVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) GetRandomFeedLoggedOut(ctx context.Context, in *dto.GetRandomFeedLoggedOutRequest, opts ...grpc.CallOption) (*dto.GetRandomFeedLoggedOutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.GetRandomFeedLoggedOutResponse)
	err := c.cc.Invoke(ctx, BrainrotService_GetRandomFeedLoggedOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainrotServiceClient) GetRandomFeed(ctx context.Context, in *dto.GetRandomFeedRequest, opts ...grpc.CallOption) (*dto.GetRandomFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.GetRandomFeedResponse)
	err := c.cc.Invoke(ctx, BrainrotService_GetRandomFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrainrotServiceServer is the server API for BrainrotService service.
// All implementations must embed UnimplementedBrainrotServiceServer
// for forward compatibility.
type BrainrotServiceServer interface {
	// Video
	UploadVideo(context.Context, *dto.UploadVideoRequest) (*dto.UploadVideoResponse, error)
	GetVideoByID(context.Context, *dto.GetVideoByIDRequest) (*dto.GetVideoByIDResponse, error)
	GetUserVideo(context.Context, *dto.GetUserVideoRequest) (*dto.GetUserVideoResponse, error)
	DeleteUserVideo(context.Context, *dto.DeleteUserVideoRequest) (*dto.DeleteUserVideoResponse, error)
	// Comment
	AddComment(context.Context, *dto.AddCommentRequest) (*dto.AddCommentResponse, error)
	GetCommentsByVideo(context.Context, *dto.GetCommentsByVideoRequest) (*dto.GetCommentsByVideoResponse, error)
	DeleteComment(context.Context, *dto.DeleteCommentRequest) (*dto.DeleteCommentResponse, error)
	// Reply
	AddReply(context.Context, *dto.AddReplyRequest) (*dto.AddReplyResponse, error)
	GetRepliesByComment(context.Context, *dto.GetRepliesByCommentRequest) (*dto.GetRepliesByCommentResponse, error)
	DeleteReply(context.Context, *dto.DeleteReplyRequest) (*dto.DeleteReplyResponse, error)
	// Like Video
	LikeVideo(context.Context, *dto.LikeVideoRequest) (*dto.LikeVideoResponse, error)
	UnlikeVideo(context.Context, *dto.UnlikeVideoRequest) (*dto.UnlikeVideoResponse, error)
	IsVideoLiked(context.Context, *dto.IsVideoLikedRequest) (*dto.IsVideoLikedResponse, error)
	// Like Comment
	LikeComment(context.Context, *dto.LikeCommentRequest) (*dto.LikeCommentResponse, error)
	UnlikeComment(context.Context, *dto.UnlikeCommentRequest) (*dto.UnlikeCommentResponse, error)
	IsCommentLiked(context.Context, *dto.IsCommentLikedRequest) (*dto.IsCommentLikedResponse, error)
	// Like Reply
	LikeReply(context.Context, *dto.LikeReplyRequest) (*dto.LikeReplyResponse, error)
	UnlikeReply(context.Context, *dto.UnlikeReplyRequest) (*dto.UnlikeReplyResponse, error)
	IsReplyLiked(context.Context, *dto.IsReplyLikedRequest) (*dto.IsReplyLikedResponse, error)
	// WatchHistory & Feed
	WatchVideo(context.Context, *dto.WatchVideoRequest) (*dto.WatchVideoResponse, error)
	GetRandomFeedLoggedOut(context.Context, *dto.GetRandomFeedLoggedOutRequest) (*dto.GetRandomFeedLoggedOutResponse, error)
	GetRandomFeed(context.Context, *dto.GetRandomFeedRequest) (*dto.GetRandomFeedResponse, error)
	mustEmbedUnimplementedBrainrotServiceServer()
}

// UnimplementedBrainrotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrainrotServiceServer struct{}

func (UnimplementedBrainrotServiceServer) UploadVideo(context.Context, *dto.UploadVideoRequest) (*dto.UploadVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadVideo not implemented")
}
func (UnimplementedBrainrotServiceServer) GetVideoByID(context.Context, *dto.GetVideoByIDRequest) (*dto.GetVideoByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoByID not implemented")
}
func (UnimplementedBrainrotServiceServer) GetUserVideo(context.Context, *dto.GetUserVideoRequest) (*dto.GetUserVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserVideo not implemented")
}
func (UnimplementedBrainrotServiceServer) DeleteUserVideo(context.Context, *dto.DeleteUserVideoRequest) (*dto.DeleteUserVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserVideo not implemented")
}
func (UnimplementedBrainrotServiceServer) AddComment(context.Context, *dto.AddCommentRequest) (*dto.AddCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddComment not implemented")
}
func (UnimplementedBrainrotServiceServer) GetCommentsByVideo(context.Context, *dto.GetCommentsByVideoRequest) (*dto.GetCommentsByVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentsByVideo not implemented")
}
func (UnimplementedBrainrotServiceServer) DeleteComment(context.Context, *dto.DeleteCommentRequest) (*dto.DeleteCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedBrainrotServiceServer) AddReply(context.Context, *dto.AddReplyRequest) (*dto.AddReplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddReply not implemented")
}
func (UnimplementedBrainrotServiceServer) GetRepliesByComment(context.Context, *dto.GetRepliesByCommentRequest) (*dto.GetRepliesByCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepliesByComment not implemented")
}
func (UnimplementedBrainrotServiceServer) DeleteReply(context.Context, *dto.DeleteReplyRequest) (*dto.DeleteReplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReply not implemented")
}
func (UnimplementedBrainrotServiceServer) LikeVideo(context.Context, *dto.LikeVideoRequest) (*dto.LikeVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeVideo not implemented")
}
func (UnimplementedBrainrotServiceServer) UnlikeVideo(context.Context, *dto.UnlikeVideoRequest) (*dto.UnlikeVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlikeVideo not implemented")
}
func (UnimplementedBrainrotServiceServer) IsVideoLiked(context.Context, *dto.IsVideoLikedRequest) (*dto.IsVideoLikedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsVideoLiked not implemented")
}
func (UnimplementedBrainrotServiceServer) LikeComment(context.Context, *dto.LikeCommentRequest) (*dto.LikeCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeComment not implemented")
}
func (UnimplementedBrainrotServiceServer) UnlikeComment(context.Context, *dto.UnlikeCommentRequest) (*dto.UnlikeCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlikeComment not implemented")
}
func (UnimplementedBrainrotServiceServer) IsCommentLiked(context.Context, *dto.IsCommentLikedRequest) (*dto.IsCommentLikedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsCommentLiked not implemented")
}
func (UnimplementedBrainrotServiceServer) LikeReply(context.Context, *dto.LikeReplyRequest) (*dto.LikeReplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeReply not implemented")
}
func (UnimplementedBrainrotServiceServer) UnlikeReply(context.Context, *dto.UnlikeReplyRequest) (*dto.UnlikeReplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlikeReply not implemented")
}
func (UnimplementedBrainrotServiceServer) IsReplyLiked(context.Context, *dto.IsReplyLikedRequest) (*dto.IsReplyLikedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReplyLiked not implemented")
}
func (UnimplementedBrainrotServiceServer) WatchVideo(context.Context, *dto.WatchVideoRequest) (*dto.WatchVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WatchVideo not implemented")
}
func (UnimplementedBrainrotServiceServer) GetRandomFeedLoggedOut(context.Context, *dto.GetRandomFeedLoggedOutRequest) (*dto.GetRandomFeedLoggedOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomFeedLoggedOut not implemented")
}
func (UnimplementedBrainrotServiceServer) GetRandomFeed(context.Context, *dto.GetRandomFeedRequest) (*dto.GetRandomFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomFeed not implemented")
}
func (UnimplementedBrainrotServiceServer) mustEmbedUnimplementedBrainrotServiceServer() {}
func (UnimplementedBrainrotServiceServer) testEmbeddedByValue()                         {}

// UnsafeBrainrotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrainrotServiceServer will
// result in compilation errors.
type UnsafeBrainrotServiceServer interface {
	mustEmbedUnimplementedBrainrotServiceServer()
}

func RegisterBrainrotServiceServer(s grpc.ServiceRegistrar, srv BrainrotServiceServer) {
	// If the following call pancis, it indicates UnimplementedBrainrotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrainrotService_ServiceDesc, srv)
}

func _BrainrotService_UploadVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.UploadVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).UploadVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_UploadVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).UploadVideo(ctx, req.(*dto.UploadVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_GetVideoByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.GetVideoByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).GetVideoByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_GetVideoByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).GetVideoByID(ctx, req.(*dto.GetVideoByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_GetUserVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.GetUserVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).GetUserVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_GetUserVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).GetUserVideo(ctx, req.(*dto.GetUserVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_DeleteUserVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.DeleteUserVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).DeleteUserVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_DeleteUserVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).DeleteUserVideo(ctx, req.(*dto.DeleteUserVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_AddComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.AddCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).AddComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_AddComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).AddComment(ctx, req.(*dto.AddCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_GetCommentsByVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.GetCommentsByVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).GetCommentsByVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_GetCommentsByVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).GetCommentsByVideo(ctx, req.(*dto.GetCommentsByVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).DeleteComment(ctx, req.(*dto.DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_AddReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.AddReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).AddReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_AddReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).AddReply(ctx, req.(*dto.AddReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_GetRepliesByComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.GetRepliesByCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).GetRepliesByComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_GetRepliesByComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).GetRepliesByComment(ctx, req.(*dto.GetRepliesByCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_DeleteReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.DeleteReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).DeleteReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_DeleteReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).DeleteReply(ctx, req.(*dto.DeleteReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_LikeVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.LikeVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).LikeVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_LikeVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).LikeVideo(ctx, req.(*dto.LikeVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_UnlikeVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.UnlikeVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).UnlikeVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_UnlikeVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).UnlikeVideo(ctx, req.(*dto.UnlikeVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_IsVideoLiked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.IsVideoLikedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).IsVideoLiked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_IsVideoLiked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).IsVideoLiked(ctx, req.(*dto.IsVideoLikedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_LikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.LikeCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).LikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_LikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).LikeComment(ctx, req.(*dto.LikeCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_UnlikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.UnlikeCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).UnlikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_UnlikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).UnlikeComment(ctx, req.(*dto.UnlikeCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_IsCommentLiked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.IsCommentLikedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).IsCommentLiked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_IsCommentLiked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).IsCommentLiked(ctx, req.(*dto.IsCommentLikedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_LikeReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.LikeReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).LikeReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_LikeReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).LikeReply(ctx, req.(*dto.LikeReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_UnlikeReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.UnlikeReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).UnlikeReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_UnlikeReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).UnlikeReply(ctx, req.(*dto.UnlikeReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_IsReplyLiked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.IsReplyLikedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).IsReplyLiked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_IsReplyLiked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).IsReplyLiked(ctx, req.(*dto.IsReplyLikedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_WatchVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.WatchVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).WatchVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_WatchVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).WatchVideo(ctx, req.(*dto.WatchVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_GetRandomFeedLoggedOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.GetRandomFeedLoggedOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).GetRandomFeedLoggedOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_GetRandomFeedLoggedOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).GetRandomFeedLoggedOut(ctx, req.(*dto.GetRandomFeedLoggedOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainrotService_GetRandomFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.GetRandomFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainrotServiceServer).GetRandomFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainrotService_GetRandomFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainrotServiceServer).GetRandomFeed(ctx, req.(*dto.GetRandomFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrainrotService_ServiceDesc is the grpc.ServiceDesc for BrainrotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrainrotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BrainrotService",
	HandlerType: (*BrainrotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadVideo",
			Handler:    _BrainrotService_UploadVideo_Handler,
		},
		{
			MethodName: "GetVideoByID",
			Handler:    _BrainrotService_GetVideoByID_Handler,
		},
		{
			MethodName: "GetUserVideo",
			Handler:    _BrainrotService_GetUserVideo_Handler,
		},
		{
			MethodName: "DeleteUserVideo",
			Handler:    _BrainrotService_DeleteUserVideo_Handler,
		},
		{
			MethodName: "AddComment",
			Handler:    _BrainrotService_AddComment_Handler,
		},
		{
			MethodName: "GetCommentsByVideo",
			Handler:    _BrainrotService_GetCommentsByVideo_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _BrainrotService_DeleteComment_Handler,
		},
		{
			MethodName: "AddReply",
			Handler:    _BrainrotService_AddReply_Handler,
		},
		{
			MethodName: "GetRepliesByComment",
			Handler:    _BrainrotService_GetRepliesByComment_Handler,
		},
		{
			MethodName: "DeleteReply",
			Handler:    _BrainrotService_DeleteReply_Handler,
		},
		{
			MethodName: "LikeVideo",
			Handler:    _BrainrotService_LikeVideo_Handler,
		},
		{
			MethodName: "UnlikeVideo",
			Handler:    _BrainrotService_UnlikeVideo_Handler,
		},
		{
			MethodName: "IsVideoLiked",
			Handler:    _BrainrotService_IsVideoLiked_Handler,
		},
		{
			MethodName: "LikeComment",
			Handler:    _BrainrotService_LikeComment_Handler,
		},
		{
			MethodName: "UnlikeComment",
			Handler:    _BrainrotService_UnlikeComment_Handler,
		},
		{
			MethodName: "IsCommentLiked",
			Handler:    _BrainrotService_IsCommentLiked_Handler,
		},
		{
			MethodName: "LikeReply",
			Handler:    _BrainrotService_LikeReply_Handler,
		},
		{
			MethodName: "UnlikeReply",
			Handler:    _BrainrotService_UnlikeReply_Handler,
		},
		{
			MethodName: "IsReplyLiked",
			Handler:    _BrainrotService_IsReplyLiked_Handler,
		},
		{
			MethodName: "WatchVideo",
			Handler:    _BrainrotService_WatchVideo_Handler,
		},
		{
			MethodName: "GetRandomFeedLoggedOut",
			Handler:    _BrainrotService_GetRandomFeedLoggedOut_Handler,
		},
		{
			MethodName: "GetRandomFeed",
			Handler:    _BrainrotService_GetRandomFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller/video_controller.proto",
}
