// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: controller/social_controller.proto

package controller

import (
	dto "github.com/Acad600-TPA/WEB-WE-251/backend/social-service/internal/adapters/inbound/dto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_controller_social_controller_proto protoreflect.FileDescriptor

const file_controller_social_controller_proto_rawDesc = "" +
	"\n" +
	"\"controller/social_controller.proto\x1a\x10dto/social.proto2\x8a\x04\n" +
	"\rSocialService\x128\n" +
	"\vSendMessage\x12\x13.SendMessageRequest\x1a\x14.SendMessageResponse\x12;\n" +
	"\fListMessages\x12\x14.ListMessagesRequest\x1a\x15.ListMessagesResponse\x128\n" +
	"\vListFriends\x12\x13.ListFriendsRequest\x1a\x14.ListFriendsResponse\x12>\n" +
	"\rListFollowing\x12\x15.ListFollowingRequest\x1a\x16.ListFollowingResponse\x12)\n" +
	"\x06Follow\x12\x0e.FollowRequest\x1a\x0f.FollowResponse\x12/\n" +
	"\bUnfollow\x12\x10.UnfollowRequest\x1a\x11.UnfollowResponse\x12>\n" +
	"\rListFollowers\x12\x15.ListFollowingRequest\x1a\x16.ListFollowingResponse\x121\n" +
	"\rSendChatEvent\x12\n" +
	".ChatEvent\x1a\x14.SendMessageResponse\x129\n" +
	"\x13SubscribeChatEvents\x12\x14.ListMessagesRequest\x1a\n" +
	".ChatEvent0\x01B_Z]github.com/Acad600-TPA/WEB-WE-251/backend/social-service/internal/adapters/inbound/controllerb\x06proto3"

var file_controller_social_controller_proto_goTypes = []any{
	(*dto.SendMessageRequest)(nil),    // 0: SendMessageRequest
	(*dto.ListMessagesRequest)(nil),   // 1: ListMessagesRequest
	(*dto.ListFriendsRequest)(nil),    // 2: ListFriendsRequest
	(*dto.ListFollowingRequest)(nil),  // 3: ListFollowingRequest
	(*dto.FollowRequest)(nil),         // 4: FollowRequest
	(*dto.UnfollowRequest)(nil),       // 5: UnfollowRequest
	(*dto.ChatEvent)(nil),             // 6: ChatEvent
	(*dto.SendMessageResponse)(nil),   // 7: SendMessageResponse
	(*dto.ListMessagesResponse)(nil),  // 8: ListMessagesResponse
	(*dto.ListFriendsResponse)(nil),   // 9: ListFriendsResponse
	(*dto.ListFollowingResponse)(nil), // 10: ListFollowingResponse
	(*dto.FollowResponse)(nil),        // 11: FollowResponse
	(*dto.UnfollowResponse)(nil),      // 12: UnfollowResponse
}
var file_controller_social_controller_proto_depIdxs = []int32{
	0,  // 0: SocialService.SendMessage:input_type -> SendMessageRequest
	1,  // 1: SocialService.ListMessages:input_type -> ListMessagesRequest
	2,  // 2: SocialService.ListFriends:input_type -> ListFriendsRequest
	3,  // 3: SocialService.ListFollowing:input_type -> ListFollowingRequest
	4,  // 4: SocialService.Follow:input_type -> FollowRequest
	5,  // 5: SocialService.Unfollow:input_type -> UnfollowRequest
	3,  // 6: SocialService.ListFollowers:input_type -> ListFollowingRequest
	6,  // 7: SocialService.SendChatEvent:input_type -> ChatEvent
	1,  // 8: SocialService.SubscribeChatEvents:input_type -> ListMessagesRequest
	7,  // 9: SocialService.SendMessage:output_type -> SendMessageResponse
	8,  // 10: SocialService.ListMessages:output_type -> ListMessagesResponse
	9,  // 11: SocialService.ListFriends:output_type -> ListFriendsResponse
	10, // 12: SocialService.ListFollowing:output_type -> ListFollowingResponse
	11, // 13: SocialService.Follow:output_type -> FollowResponse
	12, // 14: SocialService.Unfollow:output_type -> UnfollowResponse
	10, // 15: SocialService.ListFollowers:output_type -> ListFollowingResponse
	7,  // 16: SocialService.SendChatEvent:output_type -> SendMessageResponse
	6,  // 17: SocialService.SubscribeChatEvents:output_type -> ChatEvent
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_controller_social_controller_proto_init() }
func file_controller_social_controller_proto_init() {
	if File_controller_social_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_social_controller_proto_rawDesc), len(file_controller_social_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_social_controller_proto_goTypes,
		DependencyIndexes: file_controller_social_controller_proto_depIdxs,
	}.Build()
	File_controller_social_controller_proto = out.File
	file_controller_social_controller_proto_goTypes = nil
	file_controller_social_controller_proto_depIdxs = nil
}
