// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: controller/galactus_controller.proto

package controller

import (
	dto "github.com/Acad600-TPA/WEB-WE-251/galactus/internal/adapters/inbound/dto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_controller_galactus_controller_proto protoreflect.FileDescriptor

const file_controller_galactus_controller_proto_rawDesc = "" +
	"\n" +
	"$controller/galactus_controller.proto\x1a\x12dto/galactus.proto2\xdc\x06\n" +
	"\x12GalactusController\x12/\n" +
	"\bRegister\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\x12;\n" +
	"\x0eGoogleRegister\x12\x16.GoogleRegisterRequest\x1a\x11.RegisterResponse\x12&\n" +
	"\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x122\n" +
	"\vGoogleLogin\x12\x13.GoogleLoginRequest\x1a\x0e.LoginResponse\x125\n" +
	"\n" +
	"UpdateUser\x12\x12.UpdateUserRequest\x1a\x13.UpdateUserResponse\x12,\n" +
	"\aSendOTP\x12\x0f.SendOTPRequest\x1a\x10.SendOTPResponse\x12;\n" +
	"\fFindByUserId\x12\x14.FindByUserIdRequest\x1a\x15.FindByUserIdResponse\x12H\n" +
	"\x1dEnableNewFollowerNotification\x12\x15.EnableSettingRequest\x1a\x10.SettingResponse\x12D\n" +
	"\x19EnableMessageNotification\x12\x15.EnableSettingRequest\x1a\x10.SettingResponse\x12E\n" +
	"\x1aEnableMentionsNotification\x12\x15.EnableSettingRequest\x1a\x10.SettingResponse\x12B\n" +
	"\x17EnableLikeTabVisibility\x12\x15.EnableSettingRequest\x1a\x10.SettingResponse\x12?\n" +
	"\x14EnablePrivateAccount\x12\x15.EnableSettingRequest\x1a\x10.SettingResponse\x12D\n" +
	"\x13EditChatRestriction\x12\x1b.EditChatRestrictionRequest\x1a\x10.SettingResponse\x128\n" +
	"\rDeleteAccount\x12\x15.DeleteAccountRequest\x1a\x10.SettingResponseBQZOgithub.com/Acad600-TPA/WEB-WE-251/galactus/internal/adapters/inbound/controllerb\x06proto3"

var file_controller_galactus_controller_proto_goTypes = []any{
	(*dto.RegisterRequest)(nil),            // 0: RegisterRequest
	(*dto.GoogleRegisterRequest)(nil),      // 1: GoogleRegisterRequest
	(*dto.LoginRequest)(nil),               // 2: LoginRequest
	(*dto.GoogleLoginRequest)(nil),         // 3: GoogleLoginRequest
	(*dto.UpdateUserRequest)(nil),          // 4: UpdateUserRequest
	(*dto.SendOTPRequest)(nil),             // 5: SendOTPRequest
	(*dto.FindByUserIdRequest)(nil),        // 6: FindByUserIdRequest
	(*dto.EnableSettingRequest)(nil),       // 7: EnableSettingRequest
	(*dto.EditChatRestrictionRequest)(nil), // 8: EditChatRestrictionRequest
	(*dto.DeleteAccountRequest)(nil),       // 9: DeleteAccountRequest
	(*dto.RegisterResponse)(nil),           // 10: RegisterResponse
	(*dto.LoginResponse)(nil),              // 11: LoginResponse
	(*dto.UpdateUserResponse)(nil),         // 12: UpdateUserResponse
	(*dto.SendOTPResponse)(nil),            // 13: SendOTPResponse
	(*dto.FindByUserIdResponse)(nil),       // 14: FindByUserIdResponse
	(*dto.SettingResponse)(nil),            // 15: SettingResponse
}
var file_controller_galactus_controller_proto_depIdxs = []int32{
	0,  // 0: GalactusController.Register:input_type -> RegisterRequest
	1,  // 1: GalactusController.GoogleRegister:input_type -> GoogleRegisterRequest
	2,  // 2: GalactusController.Login:input_type -> LoginRequest
	3,  // 3: GalactusController.GoogleLogin:input_type -> GoogleLoginRequest
	4,  // 4: GalactusController.UpdateUser:input_type -> UpdateUserRequest
	5,  // 5: GalactusController.SendOTP:input_type -> SendOTPRequest
	6,  // 6: GalactusController.FindByUserId:input_type -> FindByUserIdRequest
	7,  // 7: GalactusController.EnableNewFollowerNotification:input_type -> EnableSettingRequest
	7,  // 8: GalactusController.EnableMessageNotification:input_type -> EnableSettingRequest
	7,  // 9: GalactusController.EnableMentionsNotification:input_type -> EnableSettingRequest
	7,  // 10: GalactusController.EnableLikeTabVisibility:input_type -> EnableSettingRequest
	7,  // 11: GalactusController.EnablePrivateAccount:input_type -> EnableSettingRequest
	8,  // 12: GalactusController.EditChatRestriction:input_type -> EditChatRestrictionRequest
	9,  // 13: GalactusController.DeleteAccount:input_type -> DeleteAccountRequest
	10, // 14: GalactusController.Register:output_type -> RegisterResponse
	10, // 15: GalactusController.GoogleRegister:output_type -> RegisterResponse
	11, // 16: GalactusController.Login:output_type -> LoginResponse
	11, // 17: GalactusController.GoogleLogin:output_type -> LoginResponse
	12, // 18: GalactusController.UpdateUser:output_type -> UpdateUserResponse
	13, // 19: GalactusController.SendOTP:output_type -> SendOTPResponse
	14, // 20: GalactusController.FindByUserId:output_type -> FindByUserIdResponse
	15, // 21: GalactusController.EnableNewFollowerNotification:output_type -> SettingResponse
	15, // 22: GalactusController.EnableMessageNotification:output_type -> SettingResponse
	15, // 23: GalactusController.EnableMentionsNotification:output_type -> SettingResponse
	15, // 24: GalactusController.EnableLikeTabVisibility:output_type -> SettingResponse
	15, // 25: GalactusController.EnablePrivateAccount:output_type -> SettingResponse
	15, // 26: GalactusController.EditChatRestriction:output_type -> SettingResponse
	15, // 27: GalactusController.DeleteAccount:output_type -> SettingResponse
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_controller_galactus_controller_proto_init() }
func file_controller_galactus_controller_proto_init() {
	if File_controller_galactus_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_galactus_controller_proto_rawDesc), len(file_controller_galactus_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_galactus_controller_proto_goTypes,
		DependencyIndexes: file_controller_galactus_controller_proto_depIdxs,
	}.Build()
	File_controller_galactus_controller_proto = out.File
	file_controller_galactus_controller_proto_goTypes = nil
	file_controller_galactus_controller_proto_depIdxs = nil
}
