// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: controller/notification_controller.proto

package controller

import (
	dto "github.com/Acad600-TPA/WEB-WE-251/notification-service/internal/adapters/inbound/dto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_controller_notification_controller_proto protoreflect.FileDescriptor

const file_controller_notification_controller_proto_rawDesc = "" +
	"\n" +
	"(controller/notification_controller.proto\x1a\x16dto/notification.proto2\xc0\x03\n" +
	"\x13NotificationService\x12_\n" +
	"\x18GetNotificationsByUserID\x12 .GetNotificationsByUserIDRequest\x1a!.GetNotificationsByUserIDResponse\x12A\n" +
	"\n" +
	"MarkAsRead\x12\x18.MarkNotificationRequest\x1a\x19.MarkNotificationResponse\x12C\n" +
	"\fMarkAsUnread\x12\x18.MarkNotificationRequest\x1a\x19.MarkNotificationResponse\x12M\n" +
	"\x12DeleteNotification\x12\x1a.DeleteNotificationRequest\x1a\x1b.DeleteNotificationResponse\x12q\n" +
	"\x1eDeleteAllNotificationsByUserID\x12&.DeleteAllNotificationsByUserIDRequest\x1a'.DeleteAllNotificationsByUserIDResponseB]Z[github.com/Acad600-TPA/WEB-WE-251/notification-service/internal/adapters/inbound/controllerb\x06proto3"

var file_controller_notification_controller_proto_goTypes = []any{
	(*dto.GetNotificationsByUserIDRequest)(nil),        // 0: GetNotificationsByUserIDRequest
	(*dto.MarkNotificationRequest)(nil),                // 1: MarkNotificationRequest
	(*dto.DeleteNotificationRequest)(nil),              // 2: DeleteNotificationRequest
	(*dto.DeleteAllNotificationsByUserIDRequest)(nil),  // 3: DeleteAllNotificationsByUserIDRequest
	(*dto.GetNotificationsByUserIDResponse)(nil),       // 4: GetNotificationsByUserIDResponse
	(*dto.MarkNotificationResponse)(nil),               // 5: MarkNotificationResponse
	(*dto.DeleteNotificationResponse)(nil),             // 6: DeleteNotificationResponse
	(*dto.DeleteAllNotificationsByUserIDResponse)(nil), // 7: DeleteAllNotificationsByUserIDResponse
}
var file_controller_notification_controller_proto_depIdxs = []int32{
	0, // 0: NotificationService.GetNotificationsByUserID:input_type -> GetNotificationsByUserIDRequest
	1, // 1: NotificationService.MarkAsRead:input_type -> MarkNotificationRequest
	1, // 2: NotificationService.MarkAsUnread:input_type -> MarkNotificationRequest
	2, // 3: NotificationService.DeleteNotification:input_type -> DeleteNotificationRequest
	3, // 4: NotificationService.DeleteAllNotificationsByUserID:input_type -> DeleteAllNotificationsByUserIDRequest
	4, // 5: NotificationService.GetNotificationsByUserID:output_type -> GetNotificationsByUserIDResponse
	5, // 6: NotificationService.MarkAsRead:output_type -> MarkNotificationResponse
	5, // 7: NotificationService.MarkAsUnread:output_type -> MarkNotificationResponse
	6, // 8: NotificationService.DeleteNotification:output_type -> DeleteNotificationResponse
	7, // 9: NotificationService.DeleteAllNotificationsByUserID:output_type -> DeleteAllNotificationsByUserIDResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_controller_notification_controller_proto_init() }
func file_controller_notification_controller_proto_init() {
	if File_controller_notification_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_notification_controller_proto_rawDesc), len(file_controller_notification_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_notification_controller_proto_goTypes,
		DependencyIndexes: file_controller_notification_controller_proto_depIdxs,
	}.Build()
	File_controller_notification_controller_proto = out.File
	file_controller_notification_controller_proto_goTypes = nil
	file_controller_notification_controller_proto_depIdxs = nil
}
