// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: dto/video.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	File          []byte                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	EnableComment bool                   `protobuf:"varint,4,opt,name=enableComment,proto3" json:"enableComment,omitempty"`
	Visibility    string                 `protobuf:"bytes,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	mi := &file_dto_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{0}
}

func (x *UploadVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadVideoRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UploadVideoRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UploadVideoRequest) GetEnableComment() bool {
	if x != nil {
		return x.EnableComment
	}
	return false
}

func (x *UploadVideoRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type UploadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Video         *Video                 `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResponse) Reset() {
	*x = UploadVideoResponse{}
	mi := &file_dto_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResponse) ProtoMessage() {}

func (x *UploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{1}
}

func (x *UploadVideoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UploadVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadVideoResponse) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

type GetVideoByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoByIDRequest) Reset() {
	*x = GetVideoByIDRequest{}
	mi := &file_dto_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoByIDRequest) ProtoMessage() {}

func (x *GetVideoByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoByIDRequest.ProtoReflect.Descriptor instead.
func (*GetVideoByIDRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{2}
}

func (x *GetVideoByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetVideoByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Video         *VideoFeed             `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoByIDResponse) Reset() {
	*x = GetVideoByIDResponse{}
	mi := &file_dto_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoByIDResponse) ProtoMessage() {}

func (x *GetVideoByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoByIDResponse.ProtoReflect.Descriptor instead.
func (*GetVideoByIDResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{3}
}

func (x *GetVideoByIDResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetVideoByIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetVideoByIDResponse) GetVideo() *VideoFeed {
	if x != nil {
		return x.Video
	}
	return nil
}

type GetUserVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserVideoRequest) Reset() {
	*x = GetUserVideoRequest{}
	mi := &file_dto_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserVideoRequest) ProtoMessage() {}

func (x *GetUserVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserVideoRequest.ProtoReflect.Descriptor instead.
func (*GetUserVideoRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserVideoRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Videos        []*VideoFeed           `protobuf:"bytes,3,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserVideoResponse) Reset() {
	*x = GetUserVideoResponse{}
	mi := &file_dto_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserVideoResponse) ProtoMessage() {}

func (x *GetUserVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserVideoResponse.ProtoReflect.Descriptor instead.
func (*GetUserVideoResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserVideoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserVideoResponse) GetVideos() []*VideoFeed {
	if x != nil {
		return x.Videos
	}
	return nil
}

type DeleteUserVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserVideoRequest) Reset() {
	*x = DeleteUserVideoRequest{}
	mi := &file_dto_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserVideoRequest) ProtoMessage() {}

func (x *DeleteUserVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserVideoRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserVideoRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUserVideoRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteUserVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserVideoResponse) Reset() {
	*x = DeleteUserVideoResponse{}
	mi := &file_dto_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserVideoResponse) ProtoMessage() {}

func (x *DeleteUserVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserVideoResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserVideoResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserVideoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteUserVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	ObjectName    string                 `protobuf:"bytes,5,opt,name=objectName,proto3" json:"objectName,omitempty"`
	EnableComment bool                   `protobuf:"varint,6,opt,name=enableComment,proto3" json:"enableComment,omitempty"`
	Visibility    string                 `protobuf:"bytes,7,opt,name=visibility,proto3" json:"visibility,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_dto_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{8}
}

func (x *Video) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Video) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *Video) GetEnableComment() bool {
	if x != nil {
		return x.EnableComment
	}
	return false
}

func (x *Video) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Video) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type VideoFeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	ObjectName    string                 `protobuf:"bytes,5,opt,name=objectName,proto3" json:"objectName,omitempty"`
	EnableComment bool                   `protobuf:"varint,6,opt,name=enableComment,proto3" json:"enableComment,omitempty"`
	Visibility    string                 `protobuf:"bytes,7,opt,name=visibility,proto3" json:"visibility,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	CommentCount  int32                  `protobuf:"varint,9,opt,name=commentCount,proto3" json:"commentCount,omitempty"`
	LikeCount     int32                  `protobuf:"varint,10,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	ViewCount     int32                  `protobuf:"varint,11,opt,name=viewCount,proto3" json:"viewCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFeed) Reset() {
	*x = VideoFeed{}
	mi := &file_dto_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFeed) ProtoMessage() {}

func (x *VideoFeed) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFeed.ProtoReflect.Descriptor instead.
func (*VideoFeed) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{9}
}

func (x *VideoFeed) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoFeed) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VideoFeed) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoFeed) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VideoFeed) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *VideoFeed) GetEnableComment() bool {
	if x != nil {
		return x.EnableComment
	}
	return false
}

func (x *VideoFeed) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *VideoFeed) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VideoFeed) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *VideoFeed) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *VideoFeed) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

type AddCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	VideoId       int32                  `protobuf:"varint,2,opt,name=videoId,proto3" json:"videoId,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_dto_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{10}
}

func (x *AddCommentRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddCommentRequest) GetVideoId() int32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *AddCommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AddCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentResponse) Reset() {
	*x = AddCommentResponse{}
	mi := &file_dto_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentResponse) ProtoMessage() {}

func (x *AddCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentResponse.ProtoReflect.Descriptor instead.
func (*AddCommentResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{11}
}

func (x *AddCommentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCommentsByVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int32                  `protobuf:"varint,1,opt,name=videoId,proto3" json:"videoId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsByVideoRequest) Reset() {
	*x = GetCommentsByVideoRequest{}
	mi := &file_dto_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsByVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsByVideoRequest) ProtoMessage() {}

func (x *GetCommentsByVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsByVideoRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsByVideoRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{12}
}

func (x *GetCommentsByVideoRequest) GetVideoId() int32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type GetCommentsByVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Comments      []*CommentFeed         `protobuf:"bytes,3,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsByVideoResponse) Reset() {
	*x = GetCommentsByVideoResponse{}
	mi := &file_dto_video_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsByVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsByVideoResponse) ProtoMessage() {}

func (x *GetCommentsByVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsByVideoResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsByVideoResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{13}
}

func (x *GetCommentsByVideoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCommentsByVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCommentsByVideoResponse) GetComments() []*CommentFeed {
	if x != nil {
		return x.Comments
	}
	return nil
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int32                  `protobuf:"varint,1,opt,name=commentId,proto3" json:"commentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_dto_video_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteCommentRequest) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_dto_video_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteCommentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	VideoId       int32                  `protobuf:"varint,3,opt,name=videoId,proto3" json:"videoId,omitempty"`
	UserId        int32                  `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_dto_video_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{16}
}

func (x *Comment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetVideoId() int32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *Comment) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CommentFeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	VideoId       int32                  `protobuf:"varint,3,opt,name=videoId,proto3" json:"videoId,omitempty"`
	UserId        int32                  `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	LikeCount     int32                  `protobuf:"varint,5,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	ReplyCount    int32                  `protobuf:"varint,6,opt,name=replyCount,proto3" json:"replyCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentFeed) Reset() {
	*x = CommentFeed{}
	mi := &file_dto_video_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentFeed) ProtoMessage() {}

func (x *CommentFeed) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentFeed.ProtoReflect.Descriptor instead.
func (*CommentFeed) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{17}
}

func (x *CommentFeed) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentFeed) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentFeed) GetVideoId() int32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CommentFeed) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentFeed) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *CommentFeed) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

type AddReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CommentId     int32                  `protobuf:"varint,2,opt,name=commentId,proto3" json:"commentId,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReplyRequest) Reset() {
	*x = AddReplyRequest{}
	mi := &file_dto_video_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplyRequest) ProtoMessage() {}

func (x *AddReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplyRequest.ProtoReflect.Descriptor instead.
func (*AddReplyRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{18}
}

func (x *AddReplyRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddReplyRequest) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *AddReplyRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AddReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReplyResponse) Reset() {
	*x = AddReplyResponse{}
	mi := &file_dto_video_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplyResponse) ProtoMessage() {}

func (x *AddReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplyResponse.ProtoReflect.Descriptor instead.
func (*AddReplyResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{19}
}

func (x *AddReplyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddReplyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRepliesByCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int32                  `protobuf:"varint,1,opt,name=commentId,proto3" json:"commentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepliesByCommentRequest) Reset() {
	*x = GetRepliesByCommentRequest{}
	mi := &file_dto_video_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepliesByCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepliesByCommentRequest) ProtoMessage() {}

func (x *GetRepliesByCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepliesByCommentRequest.ProtoReflect.Descriptor instead.
func (*GetRepliesByCommentRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{20}
}

func (x *GetRepliesByCommentRequest) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type GetRepliesByCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Replies       []*ReplyFeed           `protobuf:"bytes,3,rep,name=replies,proto3" json:"replies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepliesByCommentResponse) Reset() {
	*x = GetRepliesByCommentResponse{}
	mi := &file_dto_video_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepliesByCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepliesByCommentResponse) ProtoMessage() {}

func (x *GetRepliesByCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepliesByCommentResponse.ProtoReflect.Descriptor instead.
func (*GetRepliesByCommentResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{21}
}

func (x *GetRepliesByCommentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRepliesByCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRepliesByCommentResponse) GetReplies() []*ReplyFeed {
	if x != nil {
		return x.Replies
	}
	return nil
}

type DeleteReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int32                  `protobuf:"varint,1,opt,name=replyId,proto3" json:"replyId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplyRequest) Reset() {
	*x = DeleteReplyRequest{}
	mi := &file_dto_video_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyRequest) ProtoMessage() {}

func (x *DeleteReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyRequest.ProtoReflect.Descriptor instead.
func (*DeleteReplyRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteReplyRequest) GetReplyId() int32 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

type DeleteReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReplyResponse) Reset() {
	*x = DeleteReplyResponse{}
	mi := &file_dto_video_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReplyResponse) ProtoMessage() {}

func (x *DeleteReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReplyResponse.ProtoReflect.Descriptor instead.
func (*DeleteReplyResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteReplyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteReplyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CommentId     int32                  `protobuf:"varint,3,opt,name=commentId,proto3" json:"commentId,omitempty"`
	UserId        int32                  `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_dto_video_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{24}
}

func (x *Reply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Reply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Reply) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *Reply) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ReplyFeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CommentId     int32                  `protobuf:"varint,3,opt,name=commentId,proto3" json:"commentId,omitempty"`
	UserId        int32                  `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	LikeCount     int32                  `protobuf:"varint,6,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyFeed) Reset() {
	*x = ReplyFeed{}
	mi := &file_dto_video_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyFeed) ProtoMessage() {}

func (x *ReplyFeed) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyFeed.ProtoReflect.Descriptor instead.
func (*ReplyFeed) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{25}
}

func (x *ReplyFeed) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReplyFeed) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyFeed) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *ReplyFeed) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReplyFeed) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type LikeVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	VideoId       int32                  `protobuf:"varint,2,opt,name=videoId,proto3" json:"videoId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoRequest) Reset() {
	*x = LikeVideoRequest{}
	mi := &file_dto_video_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoRequest) ProtoMessage() {}

func (x *LikeVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoRequest.ProtoReflect.Descriptor instead.
func (*LikeVideoRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{26}
}

func (x *LikeVideoRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeVideoRequest) GetVideoId() int32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type LikeVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoResponse) Reset() {
	*x = LikeVideoResponse{}
	mi := &file_dto_video_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoResponse) ProtoMessage() {}

func (x *LikeVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoResponse.ProtoReflect.Descriptor instead.
func (*LikeVideoResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{27}
}

func (x *LikeVideoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LikeVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnlikeVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	VideoId       int32                  `protobuf:"varint,2,opt,name=videoId,proto3" json:"videoId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeVideoRequest) Reset() {
	*x = UnlikeVideoRequest{}
	mi := &file_dto_video_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeVideoRequest) ProtoMessage() {}

func (x *UnlikeVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeVideoRequest.ProtoReflect.Descriptor instead.
func (*UnlikeVideoRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{28}
}

func (x *UnlikeVideoRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlikeVideoRequest) GetVideoId() int32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type UnlikeVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeVideoResponse) Reset() {
	*x = UnlikeVideoResponse{}
	mi := &file_dto_video_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeVideoResponse) ProtoMessage() {}

func (x *UnlikeVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeVideoResponse.ProtoReflect.Descriptor instead.
func (*UnlikeVideoResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{29}
}

func (x *UnlikeVideoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnlikeVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IsVideoLikedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	VideoId       int32                  `protobuf:"varint,2,opt,name=videoId,proto3" json:"videoId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsVideoLikedRequest) Reset() {
	*x = IsVideoLikedRequest{}
	mi := &file_dto_video_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsVideoLikedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsVideoLikedRequest) ProtoMessage() {}

func (x *IsVideoLikedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsVideoLikedRequest.ProtoReflect.Descriptor instead.
func (*IsVideoLikedRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{30}
}

func (x *IsVideoLikedRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IsVideoLikedRequest) GetVideoId() int32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type IsVideoLikedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsVideoLikedResponse) Reset() {
	*x = IsVideoLikedResponse{}
	mi := &file_dto_video_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsVideoLikedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsVideoLikedResponse) ProtoMessage() {}

func (x *IsVideoLikedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsVideoLikedResponse.ProtoReflect.Descriptor instead.
func (*IsVideoLikedResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{31}
}

func (x *IsVideoLikedResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type LikeCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CommentId     int32                  `protobuf:"varint,2,opt,name=commentId,proto3" json:"commentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentRequest) Reset() {
	*x = LikeCommentRequest{}
	mi := &file_dto_video_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentRequest) ProtoMessage() {}

func (x *LikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentRequest.ProtoReflect.Descriptor instead.
func (*LikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{32}
}

func (x *LikeCommentRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeCommentRequest) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type LikeCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentResponse) Reset() {
	*x = LikeCommentResponse{}
	mi := &file_dto_video_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentResponse) ProtoMessage() {}

func (x *LikeCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentResponse.ProtoReflect.Descriptor instead.
func (*LikeCommentResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{33}
}

func (x *LikeCommentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LikeCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnlikeCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CommentId     int32                  `protobuf:"varint,2,opt,name=commentId,proto3" json:"commentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeCommentRequest) Reset() {
	*x = UnlikeCommentRequest{}
	mi := &file_dto_video_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeCommentRequest) ProtoMessage() {}

func (x *UnlikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeCommentRequest.ProtoReflect.Descriptor instead.
func (*UnlikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{34}
}

func (x *UnlikeCommentRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlikeCommentRequest) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type UnlikeCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeCommentResponse) Reset() {
	*x = UnlikeCommentResponse{}
	mi := &file_dto_video_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeCommentResponse) ProtoMessage() {}

func (x *UnlikeCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeCommentResponse.ProtoReflect.Descriptor instead.
func (*UnlikeCommentResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{35}
}

func (x *UnlikeCommentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnlikeCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IsCommentLikedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CommentId     int32                  `protobuf:"varint,2,opt,name=commentId,proto3" json:"commentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsCommentLikedRequest) Reset() {
	*x = IsCommentLikedRequest{}
	mi := &file_dto_video_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCommentLikedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCommentLikedRequest) ProtoMessage() {}

func (x *IsCommentLikedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCommentLikedRequest.ProtoReflect.Descriptor instead.
func (*IsCommentLikedRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{36}
}

func (x *IsCommentLikedRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IsCommentLikedRequest) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type IsCommentLikedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsCommentLikedResponse) Reset() {
	*x = IsCommentLikedResponse{}
	mi := &file_dto_video_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsCommentLikedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCommentLikedResponse) ProtoMessage() {}

func (x *IsCommentLikedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCommentLikedResponse.ProtoReflect.Descriptor instead.
func (*IsCommentLikedResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{37}
}

func (x *IsCommentLikedResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type LikeReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int32                  `protobuf:"varint,1,opt,name=replyId,proto3" json:"replyId,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeReplyRequest) Reset() {
	*x = LikeReplyRequest{}
	mi := &file_dto_video_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeReplyRequest) ProtoMessage() {}

func (x *LikeReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeReplyRequest.ProtoReflect.Descriptor instead.
func (*LikeReplyRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{38}
}

func (x *LikeReplyRequest) GetReplyId() int32 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *LikeReplyRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LikeReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeReplyResponse) Reset() {
	*x = LikeReplyResponse{}
	mi := &file_dto_video_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeReplyResponse) ProtoMessage() {}

func (x *LikeReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeReplyResponse.ProtoReflect.Descriptor instead.
func (*LikeReplyResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{39}
}

func (x *LikeReplyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LikeReplyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnlikeReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int32                  `protobuf:"varint,1,opt,name=replyId,proto3" json:"replyId,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeReplyRequest) Reset() {
	*x = UnlikeReplyRequest{}
	mi := &file_dto_video_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeReplyRequest) ProtoMessage() {}

func (x *UnlikeReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeReplyRequest.ProtoReflect.Descriptor instead.
func (*UnlikeReplyRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{40}
}

func (x *UnlikeReplyRequest) GetReplyId() int32 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *UnlikeReplyRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnlikeReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeReplyResponse) Reset() {
	*x = UnlikeReplyResponse{}
	mi := &file_dto_video_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeReplyResponse) ProtoMessage() {}

func (x *UnlikeReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeReplyResponse.ProtoReflect.Descriptor instead.
func (*UnlikeReplyResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{41}
}

func (x *UnlikeReplyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnlikeReplyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IsReplyLikedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int32                  `protobuf:"varint,1,opt,name=replyId,proto3" json:"replyId,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsReplyLikedRequest) Reset() {
	*x = IsReplyLikedRequest{}
	mi := &file_dto_video_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsReplyLikedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReplyLikedRequest) ProtoMessage() {}

func (x *IsReplyLikedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReplyLikedRequest.ProtoReflect.Descriptor instead.
func (*IsReplyLikedRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{42}
}

func (x *IsReplyLikedRequest) GetReplyId() int32 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *IsReplyLikedRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type IsReplyLikedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsReplyLikedResponse) Reset() {
	*x = IsReplyLikedResponse{}
	mi := &file_dto_video_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsReplyLikedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReplyLikedResponse) ProtoMessage() {}

func (x *IsReplyLikedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReplyLikedResponse.ProtoReflect.Descriptor instead.
func (*IsReplyLikedResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{43}
}

func (x *IsReplyLikedResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type WatchVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	VideoId       int32                  `protobuf:"varint,2,opt,name=videoId,proto3" json:"videoId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchVideoRequest) Reset() {
	*x = WatchVideoRequest{}
	mi := &file_dto_video_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchVideoRequest) ProtoMessage() {}

func (x *WatchVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchVideoRequest.ProtoReflect.Descriptor instead.
func (*WatchVideoRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{44}
}

func (x *WatchVideoRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WatchVideoRequest) GetVideoId() int32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type WatchVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchVideoResponse) Reset() {
	*x = WatchVideoResponse{}
	mi := &file_dto_video_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchVideoResponse) ProtoMessage() {}

func (x *WatchVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchVideoResponse.ProtoReflect.Descriptor instead.
func (*WatchVideoResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{45}
}

func (x *WatchVideoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WatchVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRandomFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomFeedRequest) Reset() {
	*x = GetRandomFeedRequest{}
	mi := &file_dto_video_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomFeedRequest) ProtoMessage() {}

func (x *GetRandomFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomFeedRequest.ProtoReflect.Descriptor instead.
func (*GetRandomFeedRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{46}
}

func (x *GetRandomFeedRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetRandomFeedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRandomFeedRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetRandomFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Videos        []*VideoFeed           `protobuf:"bytes,3,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomFeedResponse) Reset() {
	*x = GetRandomFeedResponse{}
	mi := &file_dto_video_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomFeedResponse) ProtoMessage() {}

func (x *GetRandomFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomFeedResponse.ProtoReflect.Descriptor instead.
func (*GetRandomFeedResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{47}
}

func (x *GetRandomFeedResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRandomFeedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRandomFeedResponse) GetVideos() []*VideoFeed {
	if x != nil {
		return x.Videos
	}
	return nil
}

type GetRandomFeedLoggedOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomFeedLoggedOutRequest) Reset() {
	*x = GetRandomFeedLoggedOutRequest{}
	mi := &file_dto_video_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomFeedLoggedOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomFeedLoggedOutRequest) ProtoMessage() {}

func (x *GetRandomFeedLoggedOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomFeedLoggedOutRequest.ProtoReflect.Descriptor instead.
func (*GetRandomFeedLoggedOutRequest) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{48}
}

func (x *GetRandomFeedLoggedOutRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRandomFeedLoggedOutRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetRandomFeedLoggedOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Videos        []*VideoFeed           `protobuf:"bytes,3,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomFeedLoggedOutResponse) Reset() {
	*x = GetRandomFeedLoggedOutResponse{}
	mi := &file_dto_video_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomFeedLoggedOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomFeedLoggedOutResponse) ProtoMessage() {}

func (x *GetRandomFeedLoggedOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_video_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomFeedLoggedOutResponse.ProtoReflect.Descriptor instead.
func (*GetRandomFeedLoggedOutResponse) Descriptor() ([]byte, []int) {
	return file_dto_video_proto_rawDescGZIP(), []int{49}
}

func (x *GetRandomFeedLoggedOutResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRandomFeedLoggedOutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRandomFeedLoggedOutResponse) GetVideos() []*VideoFeed {
	if x != nil {
		return x.Videos
	}
	return nil
}

var File_dto_video_proto protoreflect.FileDescriptor

const file_dto_video_proto_rawDesc = "" +
	"\n" +
	"\x0fdto/video.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n" +
	"\x12UploadVideoRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04file\x18\x02 \x01(\fR\x04file\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x05R\x06userId\x12$\n" +
	"\renableComment\x18\x04 \x01(\bR\renableComment\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tR\n" +
	"visibility\"a\n" +
	"\x13UploadVideoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\x05video\x18\x03 \x01(\v2\x06.VideoR\x05video\"%\n" +
	"\x13GetVideoByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"f\n" +
	"\x14GetVideoByIDResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\x05video\x18\x03 \x01(\v2\n" +
	".VideoFeedR\x05video\"-\n" +
	"\x13GetUserVideoRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\"h\n" +
	"\x14GetUserVideoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\x06videos\x18\x03 \x03(\v2\n" +
	".VideoFeedR\x06videos\"0\n" +
	"\x16DeleteUserVideoRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\"G\n" +
	"\x17DeleteUserVideoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf7\x01\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"objectName\x18\x05 \x01(\tR\n" +
	"objectName\x12$\n" +
	"\renableComment\x18\x06 \x01(\bR\renableComment\x12\x1e\n" +
	"\n" +
	"visibility\x18\a \x01(\tR\n" +
	"visibility\x128\n" +
	"\tcreatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xdb\x02\n" +
	"\tVideoFeed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"objectName\x18\x05 \x01(\tR\n" +
	"objectName\x12$\n" +
	"\renableComment\x18\x06 \x01(\bR\renableComment\x12\x1e\n" +
	"\n" +
	"visibility\x18\a \x01(\tR\n" +
	"visibility\x128\n" +
	"\tcreatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\"\n" +
	"\fcommentCount\x18\t \x01(\x05R\fcommentCount\x12\x1c\n" +
	"\tlikeCount\x18\n" +
	" \x01(\x05R\tlikeCount\x12\x1c\n" +
	"\tviewCount\x18\v \x01(\x05R\tviewCount\"Y\n" +
	"\x11AddCommentRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\avideoId\x18\x02 \x01(\x05R\avideoId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"B\n" +
	"\x12AddCommentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x19GetCommentsByVideoRequest\x12\x18\n" +
	"\avideoId\x18\x01 \x01(\x05R\avideoId\"t\n" +
	"\x1aGetCommentsByVideoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\bcomments\x18\x03 \x03(\v2\f.CommentFeedR\bcomments\"4\n" +
	"\x14DeleteCommentRequest\x12\x1c\n" +
	"\tcommentId\x18\x01 \x01(\x05R\tcommentId\"E\n" +
	"\x15DeleteCommentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"e\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x18\n" +
	"\avideoId\x18\x03 \x01(\x05R\avideoId\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x05R\x06userId\"\xa7\x01\n" +
	"\vCommentFeed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x18\n" +
	"\avideoId\x18\x03 \x01(\x05R\avideoId\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x05R\x06userId\x12\x1c\n" +
	"\tlikeCount\x18\x05 \x01(\x05R\tlikeCount\x12\x1e\n" +
	"\n" +
	"replyCount\x18\x06 \x01(\x05R\n" +
	"replyCount\"[\n" +
	"\x0fAddReplyRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x1c\n" +
	"\tcommentId\x18\x02 \x01(\x05R\tcommentId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"@\n" +
	"\x10AddReplyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\x1aGetRepliesByCommentRequest\x12\x1c\n" +
	"\tcommentId\x18\x01 \x01(\x05R\tcommentId\"q\n" +
	"\x1bGetRepliesByCommentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\areplies\x18\x03 \x03(\v2\n" +
	".ReplyFeedR\areplies\".\n" +
	"\x12DeleteReplyRequest\x12\x18\n" +
	"\areplyId\x18\x01 \x01(\x05R\areplyId\"C\n" +
	"\x13DeleteReplyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	"\x05Reply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\tcommentId\x18\x03 \x01(\x05R\tcommentId\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x05R\x06userId\"\x89\x01\n" +
	"\tReplyFeed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\tcommentId\x18\x03 \x01(\x05R\tcommentId\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x05R\x06userId\x12\x1c\n" +
	"\tlikeCount\x18\x06 \x01(\x05R\tlikeCount\"D\n" +
	"\x10LikeVideoRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\avideoId\x18\x02 \x01(\x05R\avideoId\"A\n" +
	"\x11LikeVideoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x12UnlikeVideoRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\avideoId\x18\x02 \x01(\x05R\avideoId\"C\n" +
	"\x13UnlikeVideoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x13IsVideoLikedRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\avideoId\x18\x02 \x01(\x05R\avideoId\",\n" +
	"\x14IsVideoLikedResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\"J\n" +
	"\x12LikeCommentRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x1c\n" +
	"\tcommentId\x18\x02 \x01(\x05R\tcommentId\"C\n" +
	"\x13LikeCommentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x14UnlikeCommentRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x1c\n" +
	"\tcommentId\x18\x02 \x01(\x05R\tcommentId\"E\n" +
	"\x15UnlikeCommentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x15IsCommentLikedRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x1c\n" +
	"\tcommentId\x18\x02 \x01(\x05R\tcommentId\".\n" +
	"\x16IsCommentLikedResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\"D\n" +
	"\x10LikeReplyRequest\x12\x18\n" +
	"\areplyId\x18\x01 \x01(\x05R\areplyId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\"A\n" +
	"\x11LikeReplyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x12UnlikeReplyRequest\x12\x18\n" +
	"\areplyId\x18\x01 \x01(\x05R\areplyId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\"C\n" +
	"\x13UnlikeReplyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x13IsReplyLikedRequest\x12\x18\n" +
	"\areplyId\x18\x01 \x01(\x05R\areplyId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\",\n" +
	"\x14IsReplyLikedResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\"E\n" +
	"\x11WatchVideoRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\avideoId\x18\x02 \x01(\x05R\avideoId\"B\n" +
	"\x12WatchVideoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\\\n" +
	"\x14GetRandomFeedRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"i\n" +
	"\x15GetRandomFeedResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\x06videos\x18\x03 \x03(\v2\n" +
	".VideoFeedR\x06videos\"M\n" +
	"\x1dGetRandomFeedLoggedOutRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"r\n" +
	"\x1eGetRandomFeedLoggedOutResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\x06videos\x18\x03 \x03(\v2\n" +
	".VideoFeedR\x06videosBRZPgithub.com/Acad600-TPA/WEB-WE-251/brainrot-service/internal/adapters/inbound/dtob\x06proto3"

var (
	file_dto_video_proto_rawDescOnce sync.Once
	file_dto_video_proto_rawDescData []byte
)

func file_dto_video_proto_rawDescGZIP() []byte {
	file_dto_video_proto_rawDescOnce.Do(func() {
		file_dto_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dto_video_proto_rawDesc), len(file_dto_video_proto_rawDesc)))
	})
	return file_dto_video_proto_rawDescData
}

var file_dto_video_proto_msgTypes = make([]protoimpl.MessageInfo, 50)
var file_dto_video_proto_goTypes = []any{
	(*UploadVideoRequest)(nil),             // 0: UploadVideoRequest
	(*UploadVideoResponse)(nil),            // 1: UploadVideoResponse
	(*GetVideoByIDRequest)(nil),            // 2: GetVideoByIDRequest
	(*GetVideoByIDResponse)(nil),           // 3: GetVideoByIDResponse
	(*GetUserVideoRequest)(nil),            // 4: GetUserVideoRequest
	(*GetUserVideoResponse)(nil),           // 5: GetUserVideoResponse
	(*DeleteUserVideoRequest)(nil),         // 6: DeleteUserVideoRequest
	(*DeleteUserVideoResponse)(nil),        // 7: DeleteUserVideoResponse
	(*Video)(nil),                          // 8: Video
	(*VideoFeed)(nil),                      // 9: VideoFeed
	(*AddCommentRequest)(nil),              // 10: AddCommentRequest
	(*AddCommentResponse)(nil),             // 11: AddCommentResponse
	(*GetCommentsByVideoRequest)(nil),      // 12: GetCommentsByVideoRequest
	(*GetCommentsByVideoResponse)(nil),     // 13: GetCommentsByVideoResponse
	(*DeleteCommentRequest)(nil),           // 14: DeleteCommentRequest
	(*DeleteCommentResponse)(nil),          // 15: DeleteCommentResponse
	(*Comment)(nil),                        // 16: Comment
	(*CommentFeed)(nil),                    // 17: CommentFeed
	(*AddReplyRequest)(nil),                // 18: AddReplyRequest
	(*AddReplyResponse)(nil),               // 19: AddReplyResponse
	(*GetRepliesByCommentRequest)(nil),     // 20: GetRepliesByCommentRequest
	(*GetRepliesByCommentResponse)(nil),    // 21: GetRepliesByCommentResponse
	(*DeleteReplyRequest)(nil),             // 22: DeleteReplyRequest
	(*DeleteReplyResponse)(nil),            // 23: DeleteReplyResponse
	(*Reply)(nil),                          // 24: Reply
	(*ReplyFeed)(nil),                      // 25: ReplyFeed
	(*LikeVideoRequest)(nil),               // 26: LikeVideoRequest
	(*LikeVideoResponse)(nil),              // 27: LikeVideoResponse
	(*UnlikeVideoRequest)(nil),             // 28: UnlikeVideoRequest
	(*UnlikeVideoResponse)(nil),            // 29: UnlikeVideoResponse
	(*IsVideoLikedRequest)(nil),            // 30: IsVideoLikedRequest
	(*IsVideoLikedResponse)(nil),           // 31: IsVideoLikedResponse
	(*LikeCommentRequest)(nil),             // 32: LikeCommentRequest
	(*LikeCommentResponse)(nil),            // 33: LikeCommentResponse
	(*UnlikeCommentRequest)(nil),           // 34: UnlikeCommentRequest
	(*UnlikeCommentResponse)(nil),          // 35: UnlikeCommentResponse
	(*IsCommentLikedRequest)(nil),          // 36: IsCommentLikedRequest
	(*IsCommentLikedResponse)(nil),         // 37: IsCommentLikedResponse
	(*LikeReplyRequest)(nil),               // 38: LikeReplyRequest
	(*LikeReplyResponse)(nil),              // 39: LikeReplyResponse
	(*UnlikeReplyRequest)(nil),             // 40: UnlikeReplyRequest
	(*UnlikeReplyResponse)(nil),            // 41: UnlikeReplyResponse
	(*IsReplyLikedRequest)(nil),            // 42: IsReplyLikedRequest
	(*IsReplyLikedResponse)(nil),           // 43: IsReplyLikedResponse
	(*WatchVideoRequest)(nil),              // 44: WatchVideoRequest
	(*WatchVideoResponse)(nil),             // 45: WatchVideoResponse
	(*GetRandomFeedRequest)(nil),           // 46: GetRandomFeedRequest
	(*GetRandomFeedResponse)(nil),          // 47: GetRandomFeedResponse
	(*GetRandomFeedLoggedOutRequest)(nil),  // 48: GetRandomFeedLoggedOutRequest
	(*GetRandomFeedLoggedOutResponse)(nil), // 49: GetRandomFeedLoggedOutResponse
	(*timestamppb.Timestamp)(nil),          // 50: google.protobuf.Timestamp
}
var file_dto_video_proto_depIdxs = []int32{
	8,  // 0: UploadVideoResponse.video:type_name -> Video
	9,  // 1: GetVideoByIDResponse.video:type_name -> VideoFeed
	9,  // 2: GetUserVideoResponse.videos:type_name -> VideoFeed
	50, // 3: Video.createdAt:type_name -> google.protobuf.Timestamp
	50, // 4: VideoFeed.createdAt:type_name -> google.protobuf.Timestamp
	17, // 5: GetCommentsByVideoResponse.comments:type_name -> CommentFeed
	25, // 6: GetRepliesByCommentResponse.replies:type_name -> ReplyFeed
	9,  // 7: GetRandomFeedResponse.videos:type_name -> VideoFeed
	9,  // 8: GetRandomFeedLoggedOutResponse.videos:type_name -> VideoFeed
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_dto_video_proto_init() }
func file_dto_video_proto_init() {
	if File_dto_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dto_video_proto_rawDesc), len(file_dto_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   50,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dto_video_proto_goTypes,
		DependencyIndexes: file_dto_video_proto_depIdxs,
		MessageInfos:      file_dto_video_proto_msgTypes,
	}.Build()
	File_dto_video_proto = out.File
	file_dto_video_proto_goTypes = nil
	file_dto_video_proto_depIdxs = nil
}
