syntax = "proto3";


option go_package = "github.com/Wenev/Survace/proto/gen/controller";
import "dto/notification.proto";

service NotificationService {
  rpc GetNotificationsByUserID(GetNotificationsByUserIDRequest) returns (GetNotificationsByUserIDResponse);
  rpc MarkAsRead(MarkNotificationRequest) returns (MarkNotificationResponse);
  rpc MarkAsUnread(MarkNotificationRequest) returns (MarkNotificationResponse);
  rpc DeleteNotification(DeleteNotificationRequest) returns (DeleteNotificationResponse);
  rpc DeleteAllNotificationsByUserID(DeleteAllNotificationsByUserIDRequest) returns (DeleteAllNotificationsByUserIDResponse);
  rpc SendNotification(SendNotificationRequest) returns (SendNotificationResponse);
}
