syntax = "proto3";

option go_package = "github.com/Wenev/Survace/proto/gen/controller";
import "dto/stream.proto";

service StreamService {

  rpc StreamChat(stream StreamChatMessage) returns (stream StreamChatMessage);
  rpc GetStreamToken(GetStreamTokenRequest) returns (GetStreamTokenResponse);

  rpc GetLiveStreamId(GetLiveStreamIdRequest) returns (GetLiveStreamIdResponse);

  rpc IsUserLive(IsUserLiveRequest) returns (IsUserLiveResponse);

  rpc GoLive(GoLiveRequest) returns (GoLiveResponse);

  rpc StopLive(StopLiveRequest) returns (StopLiveResponse);

  rpc ListLiveStreams(ListLiveStreamsRequest) returns (ListLiveStreamsResponse);
}

