syntax = "proto3";

option go_package = "github.com/Wenev/Survace/proto/gen/controller";
import "dto/video.proto";

service BrainrotService {
  rpc UploadVideo(UploadVideoRequest) returns (UploadVideoResponse);
  rpc GetVideoByID(GetVideoByIDRequest) returns (GetVideoByIDResponse);
  rpc GetUserVideo(GetUserVideoRequest) returns (GetUserVideoResponse);
  rpc DeleteUserVideo(DeleteUserVideoRequest) returns (DeleteUserVideoResponse);
  rpc GetUserVideoAndDraft(GetUserVideoAndDraftRequest) returns (GetUserVideoAndDraftResponse);
  rpc DeleteVideoByID(DeleteVideoByIDRequest) returns (DeleteVideoByIDResponse);
  rpc UpdateVideo(UpdateVideoRequest) returns (UpdateVideoResponse);

  rpc AddComment(AddCommentRequest) returns (AddCommentResponse);
  rpc GetCommentsByVideo(GetCommentsByVideoRequest) returns (GetCommentsByVideoResponse);
  rpc DeleteComment(DeleteCommentRequest) returns (DeleteCommentResponse);

  rpc AddReply(AddReplyRequest) returns (AddReplyResponse);
  rpc GetRepliesByComment(GetRepliesByCommentRequest) returns (GetRepliesByCommentResponse);
  rpc DeleteReply(DeleteReplyRequest) returns (DeleteReplyResponse);

  rpc LikeVideo(LikeVideoRequest) returns (LikeVideoResponse);
  rpc UnlikeVideo(UnlikeVideoRequest) returns (UnlikeVideoResponse);
  rpc IsVideoLiked(IsVideoLikedRequest) returns (IsVideoLikedResponse);

  rpc LikeComment(LikeCommentRequest) returns (LikeCommentResponse);
  rpc UnlikeComment(UnlikeCommentRequest) returns (UnlikeCommentResponse);
  rpc IsCommentLiked(IsCommentLikedRequest) returns (IsCommentLikedResponse);

  rpc LikeReply(LikeReplyRequest) returns (LikeReplyResponse);
  rpc UnlikeReply(UnlikeReplyRequest) returns (UnlikeReplyResponse);
  rpc IsReplyLiked(IsReplyLikedRequest) returns (IsReplyLikedResponse);

  rpc WatchVideo(WatchVideoRequest) returns (WatchVideoResponse);
  rpc GetRandomFeedLoggedOut(GetRandomFeedLoggedOutRequest) returns (GetRandomFeedLoggedOutResponse);
  rpc GetRandomFeed(GetRandomFeedRequest) returns (GetRandomFeedResponse);

  rpc SearchVideo(SearchVideoRequest) returns (SearchVideoResponse);
  rpc CreatePlaylist(CreatePlaylistRequest) returns (CreatePlaylistResponse);
  rpc DeletePlaylist(DeletePlaylistRequest) returns (DeletePlaylistResponse);
  rpc AddVideoToPlaylist(AddVideoToPlaylistRequest) returns (AddVideoToPlaylistResponse);
  rpc RemoveVideoFromPlaylist(RemoveVideoFromPlaylistRequest) returns (RemoveVideoFromPlaylistResponse);
  rpc ReorderVideo(ReorderVideoRequest) returns (ReorderVideoResponse);
  rpc GetUserPlaylists(GetUserPlaylistsRequest) returns (GetUserPlaylistsResponse);
  rpc GetPlaylistById(GetPlaylistByIdRequest) returns (GetPlaylistByIdResponse);
  rpc FriendVideo(FriendVideoRequest) returns (FriendVideoResponse);
  rpc FollowingVideo(FollowingVideoRequest) returns (FollowingVideoResponse);
  rpc UpdatePlaylistTitle(UpdatePlaylistTitleRequest) returns (UpdatePlaylistTitleResponse);
}