// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: controller/stream_controller.proto

package controller

import (
	context "context"
	dto "github.com/Acad600-TPA/WEB-WE-251/stream-service/internal/adapters/inbound/dto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamService_StreamChat_FullMethodName      = "/StreamService/StreamChat"
	StreamService_GetStreamToken_FullMethodName  = "/StreamService/GetStreamToken"
	StreamService_GetLiveStreamId_FullMethodName = "/StreamService/GetLiveStreamId"
	StreamService_IsUserLive_FullMethodName      = "/StreamService/IsUserLive"
	StreamService_GoLive_FullMethodName          = "/StreamService/GoLive"
	StreamService_StopLive_FullMethodName        = "/StreamService/StopLive"
	StreamService_ListLiveStreams_FullMethodName = "/StreamService/ListLiveStreams"
)

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamServiceClient interface {
	StreamChat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[dto.StreamChatMessage, dto.StreamChatMessage], error)
	// Get a Stream JWT token for a user (streamer)
	GetStreamToken(ctx context.Context, in *dto.GetStreamTokenRequest, opts ...grpc.CallOption) (*dto.GetStreamTokenResponse, error)
	// Fetch the stream id for a user if live (viewer)
	GetLiveStreamId(ctx context.Context, in *dto.GetLiveStreamIdRequest, opts ...grpc.CallOption) (*dto.GetLiveStreamIdResponse, error)
	// Check if a specific user is live
	IsUserLive(ctx context.Context, in *dto.IsUserLiveRequest, opts ...grpc.CallOption) (*dto.IsUserLiveResponse, error)
	// Go Live for user live check
	GoLive(ctx context.Context, in *dto.GoLiveRequest, opts ...grpc.CallOption) (*dto.GoLiveResponse, error)
	// Stop a live stream for a user
	StopLive(ctx context.Context, in *dto.StopLiveRequest, opts ...grpc.CallOption) (*dto.StopLiveResponse, error)
	// List all current live streams
	ListLiveStreams(ctx context.Context, in *dto.ListLiveStreamsRequest, opts ...grpc.CallOption) (*dto.ListLiveStreamsResponse, error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) StreamChat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[dto.StreamChatMessage, dto.StreamChatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[0], StreamService_StreamChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[dto.StreamChatMessage, dto.StreamChatMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamChatClient = grpc.BidiStreamingClient[dto.StreamChatMessage, dto.StreamChatMessage]

func (c *streamServiceClient) GetStreamToken(ctx context.Context, in *dto.GetStreamTokenRequest, opts ...grpc.CallOption) (*dto.GetStreamTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.GetStreamTokenResponse)
	err := c.cc.Invoke(ctx, StreamService_GetStreamToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetLiveStreamId(ctx context.Context, in *dto.GetLiveStreamIdRequest, opts ...grpc.CallOption) (*dto.GetLiveStreamIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.GetLiveStreamIdResponse)
	err := c.cc.Invoke(ctx, StreamService_GetLiveStreamId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) IsUserLive(ctx context.Context, in *dto.IsUserLiveRequest, opts ...grpc.CallOption) (*dto.IsUserLiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.IsUserLiveResponse)
	err := c.cc.Invoke(ctx, StreamService_IsUserLive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GoLive(ctx context.Context, in *dto.GoLiveRequest, opts ...grpc.CallOption) (*dto.GoLiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.GoLiveResponse)
	err := c.cc.Invoke(ctx, StreamService_GoLive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) StopLive(ctx context.Context, in *dto.StopLiveRequest, opts ...grpc.CallOption) (*dto.StopLiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.StopLiveResponse)
	err := c.cc.Invoke(ctx, StreamService_StopLive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) ListLiveStreams(ctx context.Context, in *dto.ListLiveStreamsRequest, opts ...grpc.CallOption) (*dto.ListLiveStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.ListLiveStreamsResponse)
	err := c.cc.Invoke(ctx, StreamService_ListLiveStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility.
type StreamServiceServer interface {
	StreamChat(grpc.BidiStreamingServer[dto.StreamChatMessage, dto.StreamChatMessage]) error
	// Get a Stream JWT token for a user (streamer)
	GetStreamToken(context.Context, *dto.GetStreamTokenRequest) (*dto.GetStreamTokenResponse, error)
	// Fetch the stream id for a user if live (viewer)
	GetLiveStreamId(context.Context, *dto.GetLiveStreamIdRequest) (*dto.GetLiveStreamIdResponse, error)
	// Check if a specific user is live
	IsUserLive(context.Context, *dto.IsUserLiveRequest) (*dto.IsUserLiveResponse, error)
	// Go Live for user live check
	GoLive(context.Context, *dto.GoLiveRequest) (*dto.GoLiveResponse, error)
	// Stop a live stream for a user
	StopLive(context.Context, *dto.StopLiveRequest) (*dto.StopLiveResponse, error)
	// List all current live streams
	ListLiveStreams(context.Context, *dto.ListLiveStreamsRequest) (*dto.ListLiveStreamsResponse, error)
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamServiceServer struct{}

func (UnimplementedStreamServiceServer) StreamChat(grpc.BidiStreamingServer[dto.StreamChatMessage, dto.StreamChatMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamChat not implemented")
}
func (UnimplementedStreamServiceServer) GetStreamToken(context.Context, *dto.GetStreamTokenRequest) (*dto.GetStreamTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStreamToken not implemented")
}
func (UnimplementedStreamServiceServer) GetLiveStreamId(context.Context, *dto.GetLiveStreamIdRequest) (*dto.GetLiveStreamIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLiveStreamId not implemented")
}
func (UnimplementedStreamServiceServer) IsUserLive(context.Context, *dto.IsUserLiveRequest) (*dto.IsUserLiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUserLive not implemented")
}
func (UnimplementedStreamServiceServer) GoLive(context.Context, *dto.GoLiveRequest) (*dto.GoLiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoLive not implemented")
}
func (UnimplementedStreamServiceServer) StopLive(context.Context, *dto.StopLiveRequest) (*dto.StopLiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopLive not implemented")
}
func (UnimplementedStreamServiceServer) ListLiveStreams(context.Context, *dto.ListLiveStreamsRequest) (*dto.ListLiveStreamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLiveStreams not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}
func (UnimplementedStreamServiceServer) testEmbeddedByValue()                       {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_StreamChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).StreamChat(&grpc.GenericServerStream[dto.StreamChatMessage, dto.StreamChatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamChatServer = grpc.BidiStreamingServer[dto.StreamChatMessage, dto.StreamChatMessage]

func _StreamService_GetStreamToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.GetStreamTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetStreamToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GetStreamToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetStreamToken(ctx, req.(*dto.GetStreamTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetLiveStreamId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.GetLiveStreamIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetLiveStreamId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GetLiveStreamId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetLiveStreamId(ctx, req.(*dto.GetLiveStreamIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_IsUserLive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.IsUserLiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).IsUserLive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_IsUserLive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).IsUserLive(ctx, req.(*dto.IsUserLiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GoLive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.GoLiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GoLive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GoLive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GoLive(ctx, req.(*dto.GoLiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_StopLive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.StopLiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).StopLive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_StopLive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).StopLive(ctx, req.(*dto.StopLiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_ListLiveStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.ListLiveStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).ListLiveStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_ListLiveStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).ListLiveStreams(ctx, req.(*dto.ListLiveStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStreamToken",
			Handler:    _StreamService_GetStreamToken_Handler,
		},
		{
			MethodName: "GetLiveStreamId",
			Handler:    _StreamService_GetLiveStreamId_Handler,
		},
		{
			MethodName: "IsUserLive",
			Handler:    _StreamService_IsUserLive_Handler,
		},
		{
			MethodName: "GoLive",
			Handler:    _StreamService_GoLive_Handler,
		},
		{
			MethodName: "StopLive",
			Handler:    _StreamService_StopLive_Handler,
		},
		{
			MethodName: "ListLiveStreams",
			Handler:    _StreamService_ListLiveStreams_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChat",
			Handler:       _StreamService_StreamChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "controller/stream_controller.proto",
}
